### ISSUE TITLE
No longer available on iTunes

### ISSUE THREAD

**Issue by bcomnes** [darvin/SparkleShare-iOS#21]
I really hope I am not doing something stupid here, but I can no longer seem to located this on iTunes.  What gives?

**Comment by fortiko** [comment]
The app is gone again :-( Would it be possible to put it on the app store again, pretty please?

**Comment by kjyv** [comment]
I have been working on lot's of little things to make the app look and behave nice on newer iphones. It also includes the ability to edit files if used with my fork of sparkleshare-dashboard. So @darvin feel free to use that version or commits from therein in case you do put it back on the app store.
